languageCode = "zh_CN" #语言
title = "君陌的Github Page" #博客标题
baseurl = "https://928234269.github.io/" #一定要用https，github强制安全措施
paginate = 5 #分页每页记录数
DisqusShortname = "君陌" #评论时显示的名字
Copyright = "All rights reserved - 2017" #版权
canonifyurls = true 

[params]
  description = "知其雄，守其雌，为天下溪。" #加段提升逼格的副标题
  cover = "images/bgi.jpg" #自己找的博客封面，要够大够酷
  author = "君陌" #文章作者
  authorlocation = "Shanghai, China" #作者位置
  authorwebsite = "https://928234269.github.io/" #作者站点
  bio= "Daocloud|软件工程师" #作者简介
  logo = "images/lufei.jpeg" #作者头像
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "928234269" #github用户名
  #twitterName = "vjeantet" 
  # facebookName = ""
  #linkedinName = "zifeng" #LinkedIn用户名
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false #是否显示Hugo水印
  #[params.social]
   #linkedin = "https://cn.linkedin.com/in/zifeng"
	
[[menu.main]] #页面菜单参数
  name = "君陌的博客"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
